### ISSUE TITLE
项目中需要增加对自定义资源文件路径的简便实现

### ISSUE THREAD

**Issue by helinjiang** [iv-web/builder-webpack3#2]
目前如果 cdn 路径是比较特别的，则还需自己再 html 文件中写一段代码，类似

```
    <% for (key in htmlWebpackPlugin.files.css) { %>
    <link rel="stylesheet" href="<%= htmlWebpackPlugin.files.css[key].replace('cdn/category/', '') %>"></link>
    <% } %>
```

和 

```
<% for (key in htmlWebpackPlugin.files.js) { %>
<script type="text/javascript"
        src="<%= htmlWebpackPlugin.files.js[key].replace('cdn/category/', '') %>"></script>
<% } %>
```

需要支持一个简便的对自定义资源文件路径的处理方案，类似一个 map 或者一个自定义函数替换

**Comment by cpselvis** [comment]
这里考虑扩展HtmlWebpackPlugin的功能，写一个插件来做路径映射。

**Comment by cpselvis** [comment]
已经支持，借助html-string-replace-webpack-plugin插件，对由html-webpack-plugin生成出来的html页面进行字符串替换，替换掉 cdn/category 类似的业务目录名称 ，在v0.2.3版本及以上可以使用此功能。在feflow.json里面需要开启inject: true 参数即可 参考https://github.com/iv-web/builder-webpack3/commit/db9f88a0818a08c6db81539cbb159d86b6e040f8
